import { ProductController } from "./controllers/product.controller";

export const ProductRouter = {
  name: "Product Catalog Management API",
  basePath: "/products",
  routes: [
    {
      path: "/",
      method: "GET",
      action: ProductController.prototype.getAllProducts,
      auth: false,
      description: "Lấy tất cả sản phẩm đang kinh doanh",
    },
    {
      path: "/all-including-out-of-stock",
      method: "GET",
      action: ProductController.prototype.getAllProductsIncludingOutOfStock,
      auth: "Manager",
      permission: { action: "read", subject: "Product" },
      description: "Lấy tất cả sản phẩm (bao gồm cả sản phẩm hết hàng)",
    },
    {
      path: "/admin/all",
      method: "GET",
      action: ProductController.prototype.getAllProductsForAdmin,
      auth: "Manager",
      permission: { action: "read", subject: "Product" },
      description: "Lấy toàn bộ sản phẩm dành cho giao diện Admin",
    },
    {
      path: "/out-of-stock",
      method: "GET",
      action: ProductController.prototype.getOutOfStockProducts,
      auth: "Manager",
      permission: { action: "read", subject: "Product" },
      description: "Xem danh sách các sản phẩm hết hàng",
    },
    {
      path: "/new",
      method: "GET",
      action: ProductController.prototype.getNewProducts,
      auth: false,
      description: "Lấy danh sách các sản phẩm mới nhất",
    },
    {
      path: "/top-selling",
      method: "GET",
      action: ProductController.prototype.getTopSellingProducts,
      auth: false,
      description: "Lấy danh sách sản phẩm nổi bật/bán chạy",
    },
    {
      path: "/search",
      method: "GET",
      action: ProductController.prototype.searchProducts,
      auth: false,
      description: "Tìm kiếm sản phẩm theo từ khóa",
    },
    {
      path: "/categories/all",
      method: "GET",
      action: ProductController.prototype.getAllCategories,
      auth: false,
      description: "Lấy danh sách tất cả các danh mục sản phẩm",
    },
    {
      path: "/categories/multiple",
      method: "GET",
      action: ProductController.prototype.getProductsByMultipleCategories,
      auth: false,
      description: "Lấy danh sách sản phẩm theo nhiều danh mục cùng lúc",
    },
    {
      path: "/category/:categoryId",
      method: "GET",
      action: ProductController.prototype.getProductsByCategory,
      auth: false,
      description: "Lấy sản phẩm theo mã danh mục",
    },
    {
      path: "/category-name/:categoryName",
      method: "GET",
      action: ProductController.prototype.getProductsByCategoryName,
      auth: false,
      description: "Lấy sản phẩm theo tên danh mục",
    },
    {
      path: "/main-category/:categoryId",
      method: "GET",
      action: ProductController.prototype.getProductsByMainCategory,
      auth: false,
      description: "Lấy sản phẩm thuộc danh mục chính",
    },
    {
      path: "/type/:type",
      method: "GET",
      action: ProductController.prototype.getProductsByType,
      auth: false,
      description: "Lấy sản phẩm theo loại (laptop, pc, accessories)",
    },
    {
      path: "/name/:name",
      method: "GET",
      action: ProductController.prototype.getProductByName,
      auth: false,
      description: "Xem chi tiết một sản phẩm theo tên sản phẩm",
    },
    {
      path: "/:id/admin",
      method: "GET",
      action: ProductController.prototype.getProductByIdForAdmin,
      auth: "Manager",
      permission: { action: "read", subject: "Product" },
      description: "Xem chi tiết sản phẩm theo ID (dành cho Admin)",
    },
    {
      path: "/:id",
      method: "GET",
      action: ProductController.prototype.getProductById,
      auth: false,
      description: "Xem chi tiết một sản phẩm theo ID",
    },
    {
      path: "/",
      method: "POST",
      action: ProductController.prototype.createProduct,
      auth: "Manager",
      permission: { action: "create", subject: "Product" },
      description: "Tạo sản phẩm thương mại mới",
    },
    {
      path: "/:id",
      method: "PUT",
      action: ProductController.prototype.updateProductPut,
      auth: "Manager",
      permission: { action: "update", subject: "Product" },
      description: "Cập nhật đè toàn bộ thông tin sản phẩm theo ID",
    },
    {
      path: "/:id",
      method: "PATCH",
      action: ProductController.prototype.updateProductPatch,
      auth: "Manager",
      permission: { action: "update", subject: "Product" },
      description: "Cập nhật một phần thông tin sản phẩm theo ID",
    },
    {
      path: "/:id",
      method: "DELETE",
      action: ProductController.prototype.deleteProduct,
      auth: "Manager",
      permission: { action: "delete", subject: "Product" },
      description: "Xóa sản phẩm theo ID",
    },
  ],
};
