/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "primary": "#b70011",
        "bg-base": "#F1F3F7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#005320",
        "surface-container-low": "#eff4ff",
        "primary-light": "#FEE2E2",
        "on-error": "#ffffff",
        "tertiary-fixed": "#7ffc97",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#002109",
        "inverse-surface": "#213145",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#410002",
        "primary-fixed": "#ffdad6",
        "outline-variant": "#e6bdb8",
        "primary-container": "#dc2626",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#111c2d",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb4ab",
        "on-primary-fixed-variant": "#93000b",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#fff6f5",
        "bg-card": "#FFFFFF",
        "secondary": "#545f73",
        "on-surface-variant": "#5c403c",
        "slate-border": "#CBD5E1",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary": "#00682b",
        "on-surface": "#0b1c30",
        "primary-hover": "#B91C1C",
        "tertiary-container": "#008438",
        "on-background": "#0b1c30",
        "outline": "#916f6b",
        "secondary-fixed-dim": "#bcc7de",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#586377",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-container": "#d5e0f8",
        "on-tertiary-container": "#e7ffe4",
        "on-primary": "#ffffff",
        "surface-tint": "#bf0715",
        "warning": "#F59E0B",
        "tertiary-fixed-dim": "#62df7d",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#ffb4ab",
        "secondary-fixed": "#d8e3fb",
        "bg-soft": "#E2E8F0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "margin-mobile": "16px",
        lg: "24px",
        sm: "8px",
        md: "16px",
        "margin-desktop": "32px",
        xl: "32px",
        gutter: "16px",
      },
      maxWidth: {
        page: "1920px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-xs": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-xl-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
      },
      keyframes: {
        slideIn: {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        spin: {
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        slideIn: "slideIn 0.6s ease-out",
        fadeInUp: "fadeInUp 0.8s ease-out",
        spin: "spin 1s linear infinite",
      },
    },
  },
  plugins: [],
};
