import { FeedbackController } from "./controllers/feedback.controller";

export const FeedbackRouter = {
  name: "Feedback Management API",
  basePath: "/feedbacks",
  routes: [
    {
      path: "/contact",
      method: "POST",
      action: FeedbackController.prototype.submitContact,
      auth: false,
      description: "Gửi yêu cầu tư vấn / liên hệ",
    },
    {
      path: "/management",
      method: "GET",
      action: FeedbackController.prototype.getManagement,
      auth: "Manager",
      description: "Manager: danh sách feedback có lọc/tìm kiếm",
    },
    {
      path: "/statistics",
      method: "GET",
      action: FeedbackController.prototype.getStatistics,
      auth: "Manager",
      description: "Manager: thống kê feedback",
    },
    {
      path: "/",
      method: "GET",
      action: FeedbackController.prototype.getAll,
      auth: false,
      description: "Lấy danh sách tất cả các đánh giá/phản hồi",
    },
    {
      path: "/paginated",
      method: "GET",
      action: FeedbackController.prototype.getPaginated,
      auth: false,
      description: "Lấy danh sách đánh giá có phân trang",
    },
    {
      path: "/product/:productId",
      method: "GET",
      action: FeedbackController.prototype.getFeedbacksByProduct,
      auth: false,
      description: "Lấy danh sách đánh giá của một sản phẩm cụ thể",
    },
    {
      path: "/export",
      method: "GET",
      action: FeedbackController.prototype.exportFeedbacks,
      auth: "Manager",
      description: "Manager: xuất dữ liệu đánh giá ra tệp Excel (.xlsx)",
    },
    {
      path: "/:id/reply",
      method: "PATCH",
      action: FeedbackController.prototype.reply,
      auth: "Manager",
      description: "Manager: phản hồi feedback",
    },
    {
      path: "/:id/hide",
      method: "PATCH",
      action: FeedbackController.prototype.toggleHide,
      auth: "Manager",
      description: "Manager: ẩn/hiện feedback",
    },
    {
      path: "/:id",
      method: "GET",
      action: FeedbackController.prototype.getOne,
      auth: false,
      description: "Xem chi tiết một đánh giá theo ID",
    },
    {
      path: "/:id",
      method: "DELETE",
      action: FeedbackController.prototype.delete,
      auth: "Manager",
      description: "Manager: xóa feedback (soft delete)",
    },
  ],
};
